import { Building2 } from 'lucide-react'
import { fmtDate } from '../../lib/helpers'

export default function EnterpriseReportHeader({ company, report, filters, generatedBy }) {
  const companyName = company?.software_name || company?.name || 'Aura Stay'
  const rawPropertyName = filters?.property && filters.property !== 'All Properties'
    ? filters.property
    : company?.name || 'All Properties'
  const propertyName = rawPropertyName && rawPropertyName !== companyName && rawPropertyName !== 'All Properties'
    ? rawPropertyName
    : ''
  const generatedAt = new Date().toLocaleString()

  return (
    <section className="enterprise-report-header">
      <div className="erp-header-brand">
        <div className="erp-logo-box">
          {company?.logo_url ? <img src={company.logo_url} alt={companyName} /> : <Building2 size={28} />}
        </div>
        <div className="erp-title-block">
          <p className="erp-company">{companyName}</p>
          <h1>{report.name}</h1>
          {propertyName && <p className="erp-property">{propertyName}</p>}
        </div>
      </div>
      <div className="erp-header-meta">
        <span>Period: <b>{fmtDate(filters.dateFrom)} to {fmtDate(filters.dateTo)}</b></span>
        <span>Currency: <b>{filters.currency || 'BDT'}</b></span>
        <span>Generated: <b>{generatedAt}</b></span>
        <span>Generated by: <b>{generatedBy || 'System'}</b></span>
      </div>
      {report.ifrsReference && (
        <div className="erp-ifrs-note">
          <b>{report.ifrsReference}</b> {report.ifrsNote}
        </div>
      )}
    </section>
  )
}
