import { Building2 } from 'lucide-react'
import { fmtDate } from '../../lib/helpers'
import './print-report.css'

/**
 * Professional report letterhead — design reference: Cloudbeds' reporting
 * conventions (consolidated brand block, report identity block, metadata
 * strip for filters/currency/cycle, audit strip for generated-by/at).
 *
 * Replaces the old ad-hoc `erp-header-brand`/`erp-logo-box`/`erp-company`
 * classes (previously defined three separate times across src/index.css)
 * with one consolidated stylesheet (print-report.css).
 */
export default function EnterpriseReportHeader({ company, report, filters }) {
  const companyName = company?.software_name || 'Aura Stay ERP'
  const propertyName = company?.name || 'Property Name Not Configured'
  const dateFrom = filters?.dateFrom ? fmtDate(filters.dateFrom) : ''
  const dateTo = filters?.dateTo ? fmtDate(filters.dateTo) : ''
  const periodLabel =
    dateFrom && dateTo && dateFrom !== dateTo
      ? `For the period ${dateFrom} - ${dateTo}`
      : dateTo
        ? `As at ${dateTo}`
        : report?.reportCategory

  return (
    <header className="erp-letterhead">
      <div className="erp-letterhead__brand">
        <div className="erp-letterhead__logo">
          {company?.logo_url ? (
            <img src={company.logo_url} alt={propertyName} />
          ) : (
            <Building2 size={20} />
          )}
        </div>
        <div>
          <p className="erp-letterhead__company-name">{propertyName}</p>
          <p className="erp-letterhead__company-meta">
            {propertyName} · {companyName}
          </p>
        </div>
      </div>

      <div className="erp-letterhead__report-id">
        <p className="erp-letterhead__report-title">{report?.name}</p>
        <p className="erp-letterhead__report-period">{periodLabel}</p>
      </div>
    </header>
  )
}

export function ReportMetaStrip({ filters }) {
  return (
    <div className="erp-meta-strip">
      <span>
        Cycle: <b>{filters?.cycle || 'Monthly'}</b>
      </span>
      <span>
        Period:{' '}
        <b>
          {filters?.dateFrom || '-'} to {filters?.dateTo || '-'}
        </b>
      </span>
      <span>
        Currency: <b>{filters?.currency || 'BDT'} (৳)</b>
      </span>
      {filters?.compareTo && filters.compareTo !== 'Off' ? (
        <span>
          Compare to: <b>{filters.compareTo}</b>
        </span>
      ) : null}
    </div>
  )
}

export function ReportAuditStrip({ generatedBy }) {
  const generatedAt = new Date().toLocaleString([], {
    year: 'numeric',
    month: 'short',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  })

  return (
    <div className="erp-audit-strip">
      <span>Generated: {generatedAt}</span>
      {generatedBy ? <span>Generated by: {generatedBy}</span> : null}
    </div>
  )
}

export function ReportSignatureFooter({ roles = ['Prepared By', 'Reviewed By', 'Approved By'] }) {
  return (
    <footer className="erp-print-footer">
      {roles.map((role) => (
        <div className="erp-signature-block" key={role}>
          <div className="erp-signature-line">{role}</div>
        </div>
      ))}
    </footer>
  )
}
