-- AEDS PR-03: tenant POS terminal mapping and Bangladesh cheque bank directory.
-- This migration supersedes manual bank selection for CARD payments.

create table if not exists public.bank_directory (
  id bigint generated by default as identity primary key,
  bank_category text,
  bank_code text not null,
  bank_name text not null,
  district_code text,
  district_name text not null,
  branch_code text,
  branch_name text not null,
  routing_number text not null unique,
  created_at timestamptz not null default now()
);

create index if not exists idx_bank_directory_bank_branch
  on public.bank_directory (bank_name, district_name, branch_name);

create table if not exists public.payment_terminals (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null,
  terminal_name text not null,
  terminal_code text,
  merchant_id text,
  bank_name text not null,
  coa_account_id uuid not null references public.chart_of_accounts(id),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, terminal_name)
);

create index if not exists idx_payment_terminals_tenant_active
  on public.payment_terminals (tenant_id, is_active, terminal_name);

alter table public.payments
  add column if not exists pos_terminal_id uuid references public.payment_terminals(id),
  add column if not exists payer_bank_name text,
  add column if not exists payer_branch_name text,
  add column if not exists payer_routing_number text;

-- CARD settles to the GL mapped to the selected tenant POS terminal.
create or replace function public.resolve_payment_account_mapping()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_account_id uuid;
  v_terminal_tenant uuid;
begin
  if upper(coalesce(new.method, '')) = 'CARD' then
    if new.pos_terminal_id is null then
      raise exception 'POS terminal is required for card payment';
    end if;

    select coa_account_id, tenant_id
      into v_account_id, v_terminal_tenant
    from public.payment_terminals
    where id = new.pos_terminal_id
      and is_active = true;

    if v_account_id is null or v_terminal_tenant is distinct from new.tenant_id then
      raise exception 'Selected POS terminal is not active for this tenant';
    end if;

    new.bank_account_id := v_account_id;
  elsif upper(coalesce(new.method, '')) in ('BANK', 'BANK_TRANSFER', 'CHEQUE') then
    if new.bank_account_id is null then
      raise exception 'Tenant bank GL account is required for % payment', new.method;
    end if;
    if upper(coalesce(new.method, '')) <> 'CARD' then
      new.pos_terminal_id := null;
    end if;
  else
    new.bank_account_id := null;
    new.pos_terminal_id := null;
  end if;

  if upper(coalesce(new.method, '')) = 'CHEQUE' then
    if nullif(btrim(new.payer_bank_name), '') is null
       or nullif(btrim(new.payer_branch_name), '') is null
       or nullif(btrim(new.payer_routing_number), '') is null then
      raise exception 'Cheque bank, branch and routing number are required';
    end if;
    if not exists (
      select 1 from public.bank_directory d
      where d.bank_name = new.payer_bank_name
        and d.branch_name = new.payer_branch_name
        and d.routing_number = new.payer_routing_number
    ) then
      raise exception 'Invalid Bangladesh bank branch or routing number';
    end if;
  else
    new.payer_bank_name := null;
    new.payer_branch_name := null;
    new.payer_routing_number := null;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_resolve_payment_account_mapping on public.payments;
create trigger trg_resolve_payment_account_mapping
before insert or update of method, pos_terminal_id, bank_account_id, tenant_id,
  payer_bank_name, payer_branch_name, payer_routing_number
on public.payments
for each row execute function public.resolve_payment_account_mapping();

-- Replace PR-02's generic CARD bank requirement with terminal mapping requirement.
alter table public.payments
  drop constraint if exists payments_bank_account_required;

alter table public.payments
  drop constraint if exists payments_card_terminal_required,
  add constraint payments_card_terminal_required
  check (upper(coalesce(method, '')) <> 'CARD' or pos_terminal_id is not null) not valid;

alter table public.payments
  drop constraint if exists payments_transfer_account_required,
  add constraint payments_transfer_account_required
  check (
    upper(coalesce(method, '')) not in ('BANK', 'BANK_TRANSFER', 'CHEQUE')
    or bank_account_id is not null
  ) not valid;

alter table public.payments
  drop constraint if exists payments_cheque_bank_required,
  add constraint payments_cheque_bank_required
  check (
    upper(coalesce(method, '')) <> 'CHEQUE'
    or (
      nullif(btrim(payer_bank_name), '') is not null
      and nullif(btrim(payer_branch_name), '') is not null
      and nullif(btrim(payer_routing_number), '') is not null
    )
  ) not valid;

-- Cross-tenant mapping protection for terminal configuration.
create or replace function public.validate_payment_terminal_account()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.chart_of_accounts coa
    where coa.id = new.coa_account_id
      and coa.tenant_id = new.tenant_id
      and coa.is_active = true
      and coa.is_bank_account = true
  ) then
    raise exception 'POS settlement account must be an active bank GL account of the same tenant';
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_validate_payment_terminal_account on public.payment_terminals;
create trigger trg_validate_payment_terminal_account
before insert or update of tenant_id, coa_account_id
on public.payment_terminals
for each row execute function public.validate_payment_terminal_account();

-- Demo helper: creates two bank GL accounts and two mapped POS terminals for any supplied tenant.
-- Run: select public.seed_demo_payment_configuration('<tenant-uuid>');
create or replace function public.seed_demo_payment_configuration(p_tenant_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_city uuid;
  v_pubali uuid;
begin
  select id into v_city from public.chart_of_accounts
   where tenant_id = p_tenant_id and code = '110201' limit 1;
  if v_city is null then
    insert into public.chart_of_accounts (tenant_id, code, name, is_active, is_bank_account)
    values (p_tenant_id, '110201', 'Demo City Bank - 9001', true, true)
    returning id into v_city;
  else
    update public.chart_of_accounts set is_bank_account = true where id = v_city;
  end if;

  select id into v_pubali from public.chart_of_accounts
   where tenant_id = p_tenant_id and code = '110202' limit 1;
  if v_pubali is null then
    insert into public.chart_of_accounts (tenant_id, code, name, is_active, is_bank_account)
    values (p_tenant_id, '110202', 'Demo Pubali Bank - 063', true, true)
    returning id into v_pubali;
  else
    update public.chart_of_accounts set is_bank_account = true where id = v_pubali;
  end if;

  insert into public.payment_terminals (tenant_id, terminal_name, terminal_code, bank_name, coa_account_id)
  values
    (p_tenant_id, 'Demo City POS', '9001', 'City Bank', v_city),
    (p_tenant_id, 'Demo Pubali POS', '063', 'Pubali Bank', v_pubali)
  on conflict (tenant_id, terminal_name) do update
    set terminal_code = excluded.terminal_code,
        bank_name = excluded.bank_name,
        coa_account_id = excluded.coa_account_id,
        is_active = true,
        updated_at = now();
end;
$$;

-- Reconciliation view: identifies invalid/missing payment method configuration without changing balances.
create or replace view public.payment_configuration_exceptions as
select
  p.id,
  p.tenant_id,
  p.payment_id,
  p.received_date,
  p.method,
  p.amount,
  case
    when upper(coalesce(p.method, '')) = 'CARD' and p.pos_terminal_id is null then 'CARD_TERMINAL_MISSING'
    when upper(coalesce(p.method, '')) in ('BANK','BANK_TRANSFER','CHEQUE') and p.bank_account_id is null then 'BANK_GL_MISSING'
    when upper(coalesce(p.method, '')) = 'CHEQUE' and nullif(btrim(p.payer_routing_number), '') is null then 'CHEQUE_ROUTING_MISSING'
    when p.bank_account_id is not null and coa.id is null then 'INVALID_OR_CROSS_TENANT_GL'
    else null
  end as exception_code
from public.payments p
left join public.chart_of_accounts coa
  on coa.id = p.bank_account_id and coa.tenant_id = p.tenant_id
where
  (upper(coalesce(p.method, '')) = 'CARD' and p.pos_terminal_id is null)
  or (upper(coalesce(p.method, '')) in ('BANK','BANK_TRANSFER','CHEQUE') and p.bank_account_id is null)
  or (upper(coalesce(p.method, '')) = 'CHEQUE' and nullif(btrim(p.payer_routing_number), '') is null)
  or (p.bank_account_id is not null and coa.id is null);

grant select on public.bank_directory to authenticated;
grant select, insert, update, delete on public.payment_terminals to authenticated;
grant select on public.payment_configuration_exceptions to authenticated;
grant execute on function public.seed_demo_payment_configuration(uuid) to authenticated;

notify pgrst, 'reload schema';
