
IF OBJECT_ID(N'dbo.notifications', N'U') IS NULL
BEGIN
	CREATE TABLE notifications(
		id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
		tenant_id UNIQUEIDENTIFIER,
		user_id UNIQUEIDENTIFIER,
		title NVARCHAR(MAX),
		body NVARCHAR(MAX),
		type NVARCHAR(255),
		is_read BIT DEFAULT 0,
		created_at DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET()
	);
END;

IF OBJECT_ID(N'dbo.activity_logs', N'U') IS NULL
BEGIN
	CREATE TABLE activity_logs(
		id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
		tenant_id UNIQUEIDENTIFIER,
		actor_id UNIQUEIDENTIFIER,
		module NVARCHAR(255),
		action NVARCHAR(255),
		entity NVARCHAR(255),
		entity_id NVARCHAR(255),
		payload NVARCHAR(MAX),
		created_at DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET()
	);
END;
