import { exportXLSX, fmtBDT, fmtDate } from '../helpers'

const escapeCsv = (value) => {
  const raw = value == null ? '' : String(value)
  return /[",\n]/.test(raw) ? `"${raw.replaceAll('"', '""')}"` : raw
}

const formatCell = (value, column) => {
  if (column?.type === 'currency') return Number(value || 0).toFixed(2)
  if (column?.type === 'date') return value ? fmtDate(value) : ''
  if (column?.type === 'percent') return `${Number(value || 0).toFixed(2)}%`
  return value ?? ''
}

export function buildReportRows(report, rows, totals = {}, meta = {}) {
  const headerRows = [
    [meta.companyName || 'Aura Stay', meta.propertyName || 'All Properties'],
    [report.name, report.reportCategory],
    [`Period: ${fmtDate(meta.dateFrom)} to ${fmtDate(meta.dateTo)}`, `Currency: ${meta.currency || 'BDT'}`],
    [`Generated: ${new Date().toLocaleString()}`, `Generated by: ${meta.generatedBy || 'System'}`],
    [],
  ]
  const tableRows = [
    report.columns.map((col) => col.label),
    ...rows.map((row) => report.columns.map((col) => formatCell(row[col.key], col))),
  ]
  const totalRow = report.columns.map((col, index) => {
    if (index === 0) return 'Grand Total'
    if (col.total) return Number(totals[col.key] || 0).toFixed(2)
    return ''
  })
  return [...headerRows, ...tableRows, totalRow]
}

export function exportReportCsv(report, rows, totals, meta) {
  const allRows = buildReportRows(report, rows, totals, meta)
  const csv = allRows.map((row) => row.map(escapeCsv).join(',')).join('\n')
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${report.code}_${meta.dateFrom}_to_${meta.dateTo}.csv`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function exportReportExcel(report, rows, totals, meta) {
  return exportXLSX(`${report.code}_${meta.dateFrom}_to_${meta.dateTo}.xlsx`, [
    { name: report.code, rows: buildReportRows(report, rows, totals, meta) },
  ])
}

export function exportReportPdf(report, rows, totals, meta) {
  const columns = report.columns
  const amount = (v) => fmtBDT(v)
  const tableHead = columns.map((col) => `<th style="width:${col.width || 120}px;text-align:${col.align || 'left'}">${col.label}</th>`).join('')
  const tableBody = rows.map((row, i) => `<tr>${columns.map((col) => {
    const val = col.type === 'currency' ? amount(row[col.key]) : formatCell(row[col.key], col)
    return `<td style="text-align:${col.align || 'left'}">${val}</td>`
  }).join('')}</tr>`).join('')
  const totalRow = `<tr class="grand">${columns.map((col, index) => {
    const val = index === 0 ? 'Grand Total' : col.total ? amount(totals[col.key]) : ''
    return `<td style="text-align:${col.align || 'left'}">${val}</td>`
  }).join('')}</tr>`
  const win = window.open('', '_blank', 'width=1280,height=900')
  if (!win) return
  win.document.write(`
    <html>
      <head>
        <title>${report.name}</title>
        <style>
          @page { size: A4 landscape; margin: 10mm; }
          body { font-family: Arial, sans-serif; color: #0f172a; }
          .top { border: 2px solid #0f3a5f; padding: 10px; margin-bottom: 8px; }
          .brand { text-align:center; color:#0f3a5f; }
          .meta { display:grid; grid-template-columns: repeat(4, 1fr); gap: 6px; font-size: 10px; margin-top: 8px; background:#eaf4ff; padding: 7px; }
          table { width:100%; border-collapse: collapse; font-size: 9px; }
          thead { display: table-header-group; }
          tfoot { display: table-row-group; }
          th { background:#0f3a5f; color:white; border:1px solid #bfd7ea; padding:6px; font-weight:700; }
          td { border:1px solid #d7e3ee; padding:5px; }
          tbody tr:nth-child(even) { background:#f8fbff; }
          .grand td { background:#dbeafe; font-weight:700; }
          .sign { display:grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-top: 22px; font-size: 10px; }
          .sign div { border-top:1px solid #0f172a; padding-top:5px; text-align:center; }
          footer { position: fixed; bottom: 0; left: 0; right: 0; text-align:center; font-size:9px; color:#64748b; }
        </style>
      </head>
      <body>
        <section class="top">
          <div class="brand">
            <h2>${meta.companyName || 'Aura Stay'}</h2>
            <div>${meta.propertyName || 'All Properties'}</div>
            <h1>${report.name}</h1>
            <strong>${report.reportCategory}</strong>
          </div>
          <div class="meta">
            <span>Period: ${fmtDate(meta.dateFrom)} to ${fmtDate(meta.dateTo)}</span>
            <span>Currency: ${meta.currency || 'BDT'}</span>
            <span>Generated: ${new Date().toLocaleString()}</span>
            <span>Generated by: ${meta.generatedBy || 'System'}</span>
          </div>
        </section>
        <table><thead><tr>${tableHead}</tr></thead><tbody>${tableBody}${totalRow}</tbody></table>
        <section class="sign"><div>Prepared by</div><div>Checked by</div><div>Approved by</div><div>Printed by</div></section>
        <footer>This report is system generated and intended for internal use only.</footer>
        <script>window.onload = () => window.print()</script>
      </body>
    </html>
  `)
  win.document.close()
}
