import {
  BarChart3,
  BedDouble,
  Boxes,
  Calculator,
  CalendarDays,
  Hotel,
  Settings,
  Utensils,
  Users,
} from "lucide-react"

export const AEDS_MODULE_REGISTRY = Object.freeze([
  {
    id: "dashboard",
    label: "Dashboard",
    path: "/dashboard",
    icon: BarChart3,
    domain: "analytics",
    permission: "dashboard",
  },
  {
    id: "reservations",
    label: "Reservations",
    path: "/reservations",
    icon: CalendarDays,
    domain: "operations",
    permission: "reservations",
  },
  {
    id: "front-office",
    label: "Front Office",
    path: "/front-office",
    icon: Hotel,
    domain: "operations",
    permission: "frontoffice",
  },
  {
    id: "housekeeping",
    label: "Housekeeping",
    path: "/housekeeping",
    icon: BedDouble,
    domain: "operations",
    permission: "housekeeping",
  },
  {
    id: "restaurant",
    label: "Restaurant",
    path: "/restaurant",
    icon: Utensils,
    domain: "operations",
    permission: "restaurant",
  },
  {
    id: "inventory",
    label: "Inventory",
    path: "/inventory",
    icon: Boxes,
    domain: "backoffice",
    permission: "inventory",
  },
  {
    id: "accounting",
    label: "Accounting",
    path: "/accounting/voucher",
    icon: Calculator,
    domain: "finance",
    permission: "accounting",
  },
  {
    id: "hr",
    label: "HR & Payroll",
    path: "/hr/employee-entry",
    icon: Users,
    domain: "backoffice",
    permission: "hr",
  },
  {
    id: "reports",
    label: "Reports",
    path: "/reports",
    icon: BarChart3,
    domain: "analytics",
    permission: "reports",
  },
  {
    id: "settings",
    label: "Settings",
    path: "/settings",
    icon: Settings,
    domain: "system",
    permission: "settings",
  },
])
