export const AEDS_PAGE_REGISTRY = Object.freeze([
  {
    id: "dashboard.home",
    moduleId: "dashboard",
    path: "/dashboard",
    title: "Executive Dashboard",
    pageType: "dashboard",
  },
  {
    id: "reservations.list",
    moduleId: "reservations",
    path: "/reservations",
    title: "Reservations",
    pageType: "list",
  },
  {
    id: "frontoffice.arrivals",
    moduleId: "front-office",
    path: "/front-office?tab=arrival-board",
    title: "Arrival Board",
    pageType: "workspace",
  },
  {
    id: "inventory.stock",
    moduleId: "inventory",
    path: "/inventory?tab=stock",
    title: "Stock Overview",
    pageType: "list",
  },
  {
    id: "accounting.voucher",
    moduleId: "accounting",
    path: "/accounting/voucher",
    title: "Voucher Entry",
    pageType: "form",
  },
  {
    id: "accounting.trial-balance",
    moduleId: "accounting",
    path: "/accounting/trial-balance",
    title: "Trial Balance",
    pageType: "report",
  },
  {
    id: "hr.employee",
    moduleId: "hr",
    path: "/hr/employee-entry",
    title: "Employee Register",
    pageType: "list",
  },
  {
    id: "restaurant.pos",
    moduleId: "restaurant",
    path: "/restaurant?tab=pos",
    title: "Restaurant POS",
    pageType: "workspace",
  },
  {
    id: "reports.center",
    moduleId: "reports",
    path: "/reports",
    title: "Reports Center",
    pageType: "report-center",
  },
])
