export const RESERVATION_STATUS = {
  DRAFT: "DRAFT",
  TENTATIVE: "TENTATIVE",
  CONFIRMED: "CONFIRMED",
  GUARANTEED: "GUARANTEED",
  CANCELLED: "CANCELLED",
  NO_SHOW: "NO_SHOW",
}

export const RESERVATION_SOURCE = {
  DIRECT: "DIRECT",
  OTA: "OTA",
  CORPORATE: "CORPORATE",
  TRAVEL_AGENT: "TRAVEL_AGENT",
  WALK_IN: "WALK_IN",
}
