-- AEDS: tenant-safe payment receipt numbering for every payment source.
-- Format: RP-{TENANT_CODE}-{8 DIGIT SEQUENCE}

alter table public.payments
  add column if not exists payment_id text;

create unique index if not exists ux_payments_payment_id
  on public.payments (payment_id)
  where payment_id is not null;

create or replace function public.payment_tenant_code(p_tenant_id uuid)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    nullif(
      upper(regexp_replace(coalesce(
        (select p.slug
           from public.properties p
          where p.tenant_id = p_tenant_id
          order by p.created_at nulls last, p.id
          limit 1),
        left(replace(p_tenant_id::text, '-', ''), 8)
      ), '[^A-Z0-9]', '', 'g')),
      ''
    ),
    'TENANT'
  );
$$;

create or replace function public.allocate_payment_reference(p_tenant_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_seq bigint;
  v_code text;
begin
  if p_tenant_id is null then
    raise exception 'Tenant is required to allocate a payment reference';
  end if;

  insert into public.tenant_sequences (tenant_id, seq_name, current_value, updated_at)
  values (p_tenant_id, 'reservation_payment', 1, now())
  on conflict (tenant_id, seq_name)
  do update set
    current_value = public.tenant_sequences.current_value + 1,
    updated_at = now()
  returning current_value into v_seq;

  v_code := public.payment_tenant_code(p_tenant_id);
  return 'RP-' || v_code || '-' || lpad(v_seq::text, 8, '0');
end;
$$;

create or replace function public.next_payment_reference()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant_id uuid;
begin
  v_tenant_id := public.current_tenant_id();
  if v_tenant_id is null then
    raise exception 'No active tenant found for current user';
  end if;
  return public.allocate_payment_reference(v_tenant_id);
end;
$$;

create or replace function public.set_payment_reference()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.tenant_id := coalesce(new.tenant_id, public.current_tenant_id());

  if new.tenant_id is null then
    raise exception 'payments.tenant_id is required';
  end if;

  if nullif(trim(new.payment_id), '') is null then
    -- Reuse a valid reference generated by older UI code; otherwise allocate centrally.
    if coalesce(new.reference, '') ~ '^RP-[A-Z0-9]+-[0-9]{8,}(\s*\||$)' then
      new.payment_id := split_part(new.reference, '|', 1);
      new.payment_id := trim(new.payment_id);
    else
      new.payment_id := public.allocate_payment_reference(new.tenant_id);
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_set_payment_reference on public.payments;
create trigger trg_set_payment_reference
before insert on public.payments
for each row
execute function public.set_payment_reference();

-- Backfill every historic payment separately, tenant by tenant.
do $$
declare
  v_row record;
begin
  for v_row in
    select id, tenant_id
      from public.payments
     where payment_id is null or trim(payment_id) = ''
     order by tenant_id, created_at nulls first, id
  loop
    update public.payments
       set payment_id = public.allocate_payment_reference(v_row.tenant_id)
     where id = v_row.id;
  end loop;
end $$;

grant execute on function public.next_payment_reference() to authenticated;
revoke all on function public.allocate_payment_reference(uuid) from public, anon, authenticated;
revoke all on function public.payment_tenant_code(uuid) from public, anon;
grant execute on function public.payment_tenant_code(uuid) to authenticated;

notify pgrst, 'reload schema';
